" Vim Configuration
" By Ryan Sandoval

" Plugins
" -------
filetype plugin indent on

" Vim Plugin auto install
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'majutsushi/tagbar'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'airblade/vim-gitgutter'
Plug 'valloric/youcompleteme'
Plug 'tpope/vim-repeat'
Plug 'mattn/emmet-vim'
Plug 'yggdroot/indentline'
Plug 'godlygeek/tabular'
call plug#end()

" Plugins Config
" --------------
" NerdCommenter
let NERDSpaceDelims=1


" Emmet only in html and css
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall


" Basic Configs
" -------------
set nu

" Search Configs
" --------------
set hlsearch
set incsearch

" Tabs and Indentation
" --------------------
set tabstop=4
set shiftwidth=4

" On pressing tab, insert 4 spaces
set expandtab

" Status Line
" -----------
let g:airline_theme='bubblegum'

" Statusline Separators
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

let g:airline_powerline_fonts = 1

" Key Mappings
" ------------

" Leader
nnoremap <SPACE> <Nop>
let mapleader="\<Space>"

" Quick Line Breaks
noremap <CR> o

" Quick Windows
noremap <C-j> <C-W><C-j>
noremap <C-h> <C-W><C-h>

noremap <C-k> <C-W><C-k>
noremap <C-l> <C-W><C-l>
